### ISSUE TITLE
x509: certificate private key does not implement crypto.Signer

### ISSUE THREAD

**Issue by flbla** [bohlenc/k8s-pod-mutator-webhook#1]
hi,

your project look like exactly what I'm looking for ! :)

I tried to deployed it with the helm chart (without changing anything) but the init container of k8s-pod-mutator-webhook is crashing with this error : level=fatal msg="x509: certificate private key does not implement crypto.Signer"

any idea why ?
thank you

**Comment by bohlenc** [comment]
Hi @flbla thanks for reporting the error :) 

It's fixed in version 1.0.1. The docker build is currently running.

Let me know if there are any other problems.

**Comment by flbla** [comment]
thanks ! it works well ! :)
